<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robot_description</name>
  <version>0.0.0</version>
  <description>Robot URDF/xacro description for kinematics sandbox</description>
  <maintainer email="woo980711@gmail.com">hhanoo</maintainer>
  <license>TODO: License declaration</license>

  <!-- ========================================================= -->
  <!-- Build tool dependencies -->
  <!-- ========================================================= -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- ========================================================= -->
  <!-- Run dependencies -->
  <!-- ========================================================= -->
  <exec_depend>xacro</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <!-- ========================================================= -->
  <!-- Test dependencies -->
  <!-- ========================================================= -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <!-- ========================================================= -->
  <!-- Export build type -->
  <!-- ========================================================= -->
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
